name: stacked_notification_cards
description: This package gives iOS style stacked notifications. And expand with a cool fan animation. It's also possible to slide each notification or when they are grouped.
repository: https://github.com/OakTree-Apps/stacked_notification_cards


version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^1.0.0-dev.9
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
